"""Tests for the human-style Queens solver. Run with:

    python -m unittest tools/test_queens_solver.py
or
    python tools/test_queens_solver.py
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import queens_solver as qs  # noqa: E402
import gen_boards  # noqa: E402

LEVELS_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "queens", "levels", "queens.json")


def board(text):
    return qs.load_board_text(text)


# Generated by tools/gen_boards.py (seed 5013): needs the "subset" technique.
SUBSET_BOARD = """
000111
000111
021111
225331
225344
225333
"""

# Generated by tools/gen_boards.py (seed 5035): needs the "chain" technique.
CHAIN_BOARD = """
1110000
1121333
4121553
4111553
4455555
5555556
5555666
"""

# Hand-made board with more than one solution.
AMBIGUOUS_BOARD = """
00011
22211
22233
44433
44433
"""


class SolverOnShippedLevels(unittest.TestCase):
    def test_all_levels_solve_and_match_brute_force(self):
        levels = qs.load_levels(LEVELS_FILE)
        self.assertGreaterEqual(len(levels), 1)
        for idx, (n, region) in enumerate(levels, 1):
            info = qs.rate(n, region)
            self.assertTrue(info["unique"], f"level {idx} not unique")
            self.assertTrue(info["solved"], f"level {idx}: {info['status']}")
            self.assertEqual(info["solution"], qs.Puzzle(n, region).brute_force()[0], f"level {idx}")
            self.assertGreater(info["score"], 0)
            self.assertIn(info["stars"], range(1, 6))
            self.assertEqual(sum(info["counts"].values()), len(info["steps"]))

    def test_steps_replay_to_solution(self):
        n, region = qs.load_levels(LEVELS_FILE)[0]
        info = qs.rate(n, region)
        p = qs.Puzzle(n, region)
        solver = qs.Solver(p)
        st = qs.State(p.all, 0)
        for s in info["steps"]:
            self.assertIn(s.technique, qs.ORDER)
            self.assertEqual(s.cost, qs.TECHNIQUES[s.technique]["cost"])
            if s.final_state is not None:
                st = s.final_state
            else:
                solver.apply(st, s)
        self.assertEqual(qs.popcount(st.queens), n)


class Techniques(unittest.TestCase):
    def test_singles_alone_do_not_solve(self):
        n, region = board(SUBSET_BOARD)
        info = qs.rate(n, region, techniques=[])
        self.assertEqual(info["status"], "stuck")
        self.assertIsNone(info["solution"])

    def test_subset_required(self):
        n, region = board(SUBSET_BOARD)
        without = qs.rate(n, region, techniques=["confined", "common"])
        self.assertEqual(without["status"], "stuck")
        with_subset = qs.rate(n, region, techniques=["confined", "common", "subset"])
        self.assertTrue(with_subset["solved"])
        self.assertEqual(with_subset["hardest"], "subset")
        self.assertEqual(with_subset["stars"], qs.TECHNIQUES["subset"]["stars"])
        self.assertEqual(qs.rate(n, region)["hardest"], "subset")

    def test_chain_required(self):
        n, region = board(CHAIN_BOARD)
        without = qs.rate(n, region, techniques=["confined", "common", "subset"])
        self.assertEqual(without["status"], "stuck")
        full = qs.rate(n, region)
        self.assertTrue(full["solved"])
        self.assertEqual(full["hardest"], "chain")
        self.assertEqual(full["counts"]["guess"], 0)

    def test_guess_alone_solves_and_costs_more(self):
        n, region = board(CHAIN_BOARD)
        full = qs.rate(n, region)
        guess_only = qs.rate(n, region, techniques=["guess"])
        self.assertTrue(guess_only["solved"])
        self.assertEqual(guess_only["solution"], full["solution"])
        self.assertEqual(guess_only["hardest"], "guess")
        self.assertEqual(guess_only["stars"], 5)
        self.assertGreater(guess_only["score"], full["score"])
        # Nested work is recorded on the guess step.
        guess_steps = [s for s in guess_only["steps"] if s.technique == "guess"]
        self.assertTrue(guess_steps)
        self.assertTrue(any(s.inner for s in guess_steps))
        self.assertTrue(all(s.cost >= qs.TECHNIQUES["guess"]["cost"] for s in guess_steps))

    def test_guess_depth_limit(self):
        n, region = board(CHAIN_BOARD)
        info = qs.rate(n, region, techniques=["guess"], max_guess_depth=0)
        self.assertEqual(info["status"], "stuck")

    def test_common_covers_confined(self):
        # "confined" is a special case of "common": both sets solve the same boards.
        for n, region in qs.load_levels(LEVELS_FILE):
            a = qs.rate(n, region, techniques=["confined", "common"])["solved"]
            b = qs.rate(n, region, techniques=["common"])["solved"]
            self.assertEqual(a, b)

    def test_costs_are_ordered(self):
        costs = [qs.TECHNIQUES[t]["cost"] for t in qs.ORDER]
        self.assertEqual(costs, sorted(costs))
        stars = [qs.TECHNIQUES[t]["stars"] for t in qs.ORDER]
        self.assertEqual(stars, sorted(stars))


class Inputs(unittest.TestCase):
    def test_ambiguous_board_is_reported(self):
        n, region = board(AMBIGUOUS_BOARD)
        p = qs.Puzzle(n, region)
        self.assertEqual(len(p.brute_force(limit=2)), 2)
        info = qs.rate(n, region)
        self.assertFalse(info["unique"])

    def test_board_text_parser(self):
        n, region = board("# comment\n01\n\n 0 1 \n")
        self.assertEqual(n, 2)
        self.assertEqual(region, [["0", "1"], ["0", "1"]])
        with self.assertRaises(ValueError):
            board("012\n012\n")
        with self.assertRaises(ValueError):
            qs.Puzzle(2, [["0", "0"], ["0", "0"]])  # not n regions

    def test_level_file(self):
        levels = qs.load_levels(LEVELS_FILE)
        for n, region in levels:
            self.assertEqual(len(region), n)
            self.assertTrue(all(len(row) == n for row in region))
        raw = gen_boards.read_levels(LEVELS_FILE)
        ids = [lv["id"] for lv in raw]
        self.assertEqual(len(set(ids)), len(ids), "level ids must be unique")
        import uuid
        for lv in raw:
            self.assertEqual(str(uuid.UUID(lv["id"])), lv["id"])
            self.assertEqual(set(lv), {"id", "size", "regions", "solution", "difficulty", "stars", "seed"})

    def test_write_read_roundtrip_keeps_ids_and_appends(self):
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "levels.json")
            self.assertEqual(gen_boards.read_levels(path), [])
            gen_boards.main([path, "--count", "2", "--min-size", "6", "--max-size", "6"])
            first = gen_boards.read_levels(path)
            self.assertEqual(len(first), 2)
            # Regenerating the same boards keeps their ids.
            gen_boards.main([path, "--count", "2", "--min-size", "6", "--max-size", "6"])
            self.assertEqual([lv["id"] for lv in gen_boards.read_levels(path)], [lv["id"] for lv in first])
            # Appending keeps the old levels in front and adds new, different boards.
            gen_boards.main([path, "--count", "1", "--min-size", "6", "--max-size", "6", "--append"])
            all_levels = gen_boards.read_levels(path)
            self.assertEqual([lv["id"] for lv in all_levels[:2]], [lv["id"] for lv in first])
            self.assertEqual(len(all_levels), 3)
            self.assertEqual(len({gen_boards.canonical(lv["regions"]) for lv in all_levels}), 3)

    def test_cli_runs(self):
        import io
        import contextlib
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = qs.main([LEVELS_FILE, "-l", "1", "-v"])
        self.assertEqual(rc, 0)
        self.assertIn("solved", buf.getvalue())
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = qs.main([LEVELS_FILE, "--json"])
        import json
        data = json.loads(buf.getvalue())
        self.assertEqual(len(data), len(qs.load_levels(LEVELS_FILE)))
        self.assertIn("score", data[0])


class Generator(unittest.TestCase):
    def test_canonical_ignores_symmetry_and_names(self):
        n, region = board(CHAIN_BOARD)
        key = gen_boards.canonical(region)
        rotated = [[region[n - 1 - c][r] for c in range(n)] for r in range(n)]
        mirrored = [row[::-1] for row in region]
        renamed = [[chr(ord("a") + int(v)) for v in row] for row in region]
        for other in (rotated, mirrored, renamed):
            self.assertEqual(gen_boards.canonical(other), key)
        n2, other_board = board(SUBSET_BOARD)
        self.assertNotEqual(gen_boards.canonical(other_board), key)

    def test_split_quota(self):
        self.assertEqual(gen_boards.split_quota(10, {1: 30, 2: 30, 3: 20, 4: 15, 5: 5}), {1: 3, 2: 3, 3: 2, 4: 2, 5: 0})
        self.assertEqual(sum(gen_boards.split_quota(7, {1: 1, 2: 1, 3: 1}).values()), 7)
        self.assertEqual(gen_boards.parse_star_weights("1:30,2:30,3:20,4:15,5:5"), {1: 30, 2: 30, 3: 20, 4: 15, 5: 5})
        with self.assertRaises(ValueError):
            gen_boards.parse_star_weights("6:1")

    def test_sizes_for_count(self):
        self.assertEqual(gen_boards.sizes_for_count(10, 6, 10), [6, 6, 7, 7, 8, 8, 9, 9, 10, 10])
        self.assertEqual(gen_boards.sizes_for_count(3, 6, 10), [6, 7, 9])
        self.assertEqual(gen_boards.sizes_for_count(1, 6, 10), [6])

    def test_generate_levels_dedups_and_fills_quota(self):
        seen = set()
        first = gen_boards.generate_levels([6, 6], seed=1000, seen=seen)
        self.assertEqual(len(first), 2)
        self.assertEqual(len(seen), 2)
        # The same seeds again are rejected as duplicates, so new boards come out.
        second = gen_boards.generate_levels([6], seed=1000, seen=seen)
        self.assertNotIn(second[0]["seed"], {lv["seed"] for lv in first})
        mixed = gen_boards.generate_levels([6, 6], seed=2000, star_weights={1: 1, 2: 1}, max_tries=100)
        self.assertEqual(sorted(lv["stars"] for lv in mixed), [1, 2])
        for lv in first + second + mixed:
            self.assertTrue(qs.rate(lv["size"], lv["regions"])["unique"])


if __name__ == "__main__":
    unittest.main()
